export const IT_CAREER_FIELDS = [
  { value: "software-development", label: "Software Development" },
  { value: "web-development", label: "Web Development" },
  { value: "mobile-development", label: "Mobile Development" },
  { value: "devops", label: "DevOps / SRE" },
  { value: "cloud-architecture", label: "Cloud Architecture" },
  { value: "data-science", label: "Data Science" },
  { value: "data-engineering", label: "Data Engineering" },
  { value: "machine-learning", label: "Machine Learning / AI" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "database-admin", label: "Database Administration" },
  { value: "network-engineering", label: "Network Engineering" },
  { value: "it-support", label: "IT Support / Help Desk" },
  { value: "systems-admin", label: "Systems Administration" },
  { value: "qa-testing", label: "QA / Testing" },
  { value: "ui-ux-design", label: "UI/UX Design" },
  { value: "technical-writing", label: "Technical Writing" },
  { value: "it-management", label: "IT Management" },
  { value: "enterprise-architecture", label: "Enterprise Architecture" },
  { value: "blockchain", label: "Blockchain Development" },
  { value: "game-development", label: "Game Development" },
  { value: "embedded-systems", label: "Embedded Systems" },
  { value: "other", label: "Other IT Field" }
]